version: '2'

services:

  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      main:
        aliases:
          - mongodb
    command: mongod

  redux-mesh-api:
    image: reduxmesh/api:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
      - MONGODB_URL=mongodb://mongodb:27017/mydb
      - JWT_SECRET=secret
    networks:
      main:
        aliases:
          - redux-mesh-api
    command: >
      /bin/bash -c "sleep 5; node ."
networks:
  main:

volumes:
  mongodb:
  yarn:
  mongodata: